# metrics docs: https://docs.tendermint.com/master/nodes/metrics.html
groups:
  - name: pundix-alerts
    rules:
      - alert: The pundix node service
        expr: up{job="pundix-node"} != 1
        for: 0m
        labels:
          level: critical
        annotations:
          description: "The pundix node service not found"

      - alert: The pundix consensus height
        expr: tendermint_consensus_height{job="pundix-node"} - (tendermint_consensus_height{job="pundix-node"} offset 1m) == 0
        for: 0m
        labels:
          level: critical
          monitor: tendermint_consensus_height
        annotations:
          description: "The pundix node does not generate a block for 1 minute"

      - alert: The pundix consensus validators
        expr: sum(tendermint_consensus_validators{job="pundix-node"} - (tendermint_consensus_validators{job="pundix-node"} offset 1m) != 0) by (job)
        for: 0m
        labels:
          level: critical
          monitor: tendermint_consensus_validators
        annotations:
          description: "The pundix consensus validators has changed, current: {{$value}}"

      - alert: The pundix node latest block height
        expr: tendermint_consensus_latest_block_height{job="pundix-node"} - (tendermint_consensus_latest_block_height{job="pundix-node"} offset 1m) == 0
        for: 0m
        labels:
          level: critical
          monitor: tendermint_consensus_latest_block_height
        annotations:
          description: "The pundix node block height does not increase for 2 minutes"

      - alert: The pundix node last signed height
        expr: tendermint_consensus_validator_last_signed_height{job="pundix-node"} - (tendermint_consensus_validator_last_signed_height{job="pundix-node"} offset 1m) == 0
        for: 0m
        labels:
          level: warning
          monitor: tendermint_consensus_validator_last_signed_height
        annotations:
          description: "The pundix node did not participate in the block signing for 2 minutes"

      - alert: The pundix node missed blocks
        expr: tendermint_consensus_validator_missed_blocks{job="pundix-node"} - (tendermint_consensus_validator_missed_blocks{job="pundix-node"} offset 1m) >= 3
        for: 1m
        labels:
          level: warning
          monitor: tendermint_consensus_validator_missed_blocks
        annotations:
          description: "The number of blocks not signed by the verifier exceeds the threshold of 100, current: {{$value}}"

      - alert: The pundix node missing validators
        expr: tendermint_consensus_missing_validators{job="pundix-node"} > 10
        for: 1m
        labels:
          level: warning
          monitor: tendermint_consensus_missing_validators
        annotations:
          description: "The pundix node missing validators number exceeds the threshold 10, current: {{$value}}"

      - alert: The pundix node byzantine validators
        expr: tendermint_consensus_byzantine_validators{job="pundix-node"} > 0
        for: 1m
        labels:
          level: warning
          monitor: tendermint_consensus_byzantine_validators
        annotations:
          description: "The pundix node byzantine validators number exceeds the threshold 0, current: {{$value}}"

      - alert: The pundix node block interval seconds
        expr: tendermint_consensus_block_interval_seconds_sum{job="pundix-node"} / tendermint_consensus_block_interval_seconds_count{job="pundix-node"} > 7
        for: 1m
        labels:
          level: warning
          monitor: tendermint_consensus_block_interval_seconds_(sum/count)
        annotations:
          description: "The pundix node block interval seconds, current: {{$value}}s"

      - alert: The pundix node consensus rounds
        expr: tendermint_consensus_rounds{job="pundix-node"} > 0
        for: 1m
        labels:
          level: warning
          monitor: tendermint_consensus_rounds
        annotations:
          description: "The pundix node number of rounds > 0, current: {{$value}}s"

      - alert: The pundix number of transactions
        expr: tendermint_consensus_num_txs{job="pundix-node"} > 100
        for: 1m
        labels:
          level: warning
          monitor: tendermint_consensus_num_txs
        annotations:
          description: "The pundix number of transactions > 100, current: {{$value}}"

      - alert: The pundix node mempool number of uncommitted transactions
        expr: tendermint_mempool_size{job="pundix-node"} > 100
        for: 1m
        labels:
          level: warning
          monitor: tendermint_mempool_size
        annotations:
          description: "The pundix node number of uncommitted transactions > 100, current: {{$value}}"

      - alert: The pundix mempool failed txs number
        expr: tendermint_mempool_failed_txs{job="pundix-node"} - (tendermint_mempool_failed_txs{job="pundix-node"} offset 1m) > 10
        for: 1m
        labels:
          level: warning
          monitor: tendermint_mempool_failed_txs
        annotations:
          description: "The pundix failed transactions number in the memory pool has increased by more than 10 in 1 minute, current: {{$value}}"

      - alert: The pundix node synchronization status
        expr: tendermint_consensus_fast_syncing{job="pundix-node"} - (tendermint_consensus_fast_syncing{job="pundix-node"} offset 1m) != 0
        for: 1m
        labels:
          level: warning
          monitor: tendermint_consensus_fast_syncing
        annotations:
          description: "The node synchronization status has changed, please check"

      - alert: The pundix node p2p peers
        expr: tendermint_p2p_peers{job="pundix-node"} < 5
        for: 1m
        labels:
          level: warning
          monitor: tendermint_p2p_peers
        annotations:
          description: "The pundix node p2p peers is lower than 5, current: {{$value}}"
